### ISSUE TITLE
Control Shift H not hiding the executed code at the bottom

### ISSUE THREAD

**Issue by AlexandreRangel** [ojack/hydra#73]
On the lattest version (2020-01-23) Control Shift H is not hiding the executed code at the bottom of the screen (Chrome Browser on Windows).

**Comment by ojack** [comment]
Fixed https://github.com/ojack/hydra/commit/0021eddd689a3ea1dd3cb00e8e8d4917e50d02b6 :)

**Comment by AlexandreRangel** [comment]
Yey!

**Comment by AlexandreRangel** [comment]
Control Shift H is still not hiding the log for me on https://hydra-editor.glitch.me
